language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - jensen5201@163.com
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - cd _book
  - git init
  - git remote add origin https://${path}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force "https://jensen5201:Git091290..@${path}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - path=github.com/jensen5201/blog.git
